### ISSUE TITLE
Any plans to create release artifacts?

### ISSUE THREAD

**Issue by steers** [greenbone/pg-gvm#12]
There have been no release artifacts or tags created for this module, so it's hard to know what version(s) of `pg-gvm` are compatible with other GVM/OpenVAS components, for which release artifacts are normally published, e.g. https://github.com/greenbone/gvm-libs/releases/tag/v21.4.0

Are there any plans to create similar source release artifacts for this module? Or is the intention to always build from `master`?

**Comment by y0urself** [comment]
I will create a first release next week.

**Comment by bjoernricks** [comment]
Of course we are going to do releases for pg-gvm. But at the moment it is only required for the in development version of GVM 21.10 Therefore no release yet.

**Comment by steers** [comment]
Thanks for the quick response!

I suppose there was some confusion around which releases this module was required for, since it's referenced in the gvmd install guide on master https://github.com/greenbone/gvmd/blob/master/INSTALL.md#setting-up-the-postgresql-database

However, it's not mentioned in the `v21.04.0` version of that document, which I should have referenced. Sorry if I offended anyone.
