### ISSUE TITLE
Does not compile in centos8 nor centos9

### ISSUE THREAD

**Issue by ssadeque464** [greenbone/pg-gvm#44]
Currently posted issue: https://forum.greenbone.net/t/gvm-checking-not-found/13537/4

Does not compile in ubi8-minimal/centos8 and ubi9-minimal/centos9.

![image](https://forum.greenbone.net/uploads/default/original/2X/a/afddf8334a339d131f8a334217d0b0328e1abb1d.jpeg)

**Comment by bjoernricks** [comment]
CentOS 8 is not supported. With CentOS 9 it should be possible to build pg-gvm (https://greenbone.github.io/docs/latest/22.4/source-build/index.html#pg-gvm).

**Comment by ssadeque464** [comment]
I was able to fix this by following the guide line by line on centos9/ubi9-minimal.
