### ISSUE TITLE
PostgreSQL vulnerability DSA-5554-1

### ISSUE THREAD

**Issue by Fedpixel** [greenbone/pg-gvm#74]
Hello,

Multiple vulnerabilities have been discovered in PostgreSQL.

They enable an attacker to cause a remote denial of service 
data breach and remote arbitrary code execution.

https://security-tracker.debian.org/tracker/DSA-5554-1

I would suggest rebuilding the docker image with an updated postgresql-13.

**Comment by bjoernricks** [comment]
Thanks for your notification. We will address this issue as soon as possible.

**Comment by Fedpixel** [comment]
Hello, 

New vulnerabilities have been discovered in PostgreSQL.

https://www.postgresql.org/about/news/postgresql-162-156-1411-1314-and-1218-released-2807/

I would suggest rebuilding the docker image with an updated postgresql-13 :

https://tracker.debian.org/news/1503767/accepted-postgresql-13-1314-0deb11u1-source-into-oldstable-security/

Cordially,
